# Check on http://lint.travis-ci.org/ after modifying!
language: python
python:
  - "2.7"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda env create -f dev-environment.yml
  - source activate picrust-dev
  - pip install . --no-deps
script:
  - pytest --cov=picrust tests/
